version: "3"
services:
  app:
    container_name: xiaoya-sync
    image: yoongger/xiaoya-sync:latest
    network_mode: host
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /volume1/docker/xiaoya/media:/data
      - /volume1/docker/xiaoya-sync/log:/log